name: Sync Files
on:
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Add Arubinu/Draco-CGRU git
        run:  git remote add draco https://github.com/Arubinu/Draco-CGRU.git
      - name: Merge Master branches
        run:  git merge draco/master --allow-unrelated-histories
      - name: Resolve conflicts favoring DRACO
        run:  git checkout --theirs -- *
